NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.Leather1-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.Leather1-cert.pem
    OrganizationalUnitIdentifier: peer
