NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.RawHide2-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.RawHide2-cert.pem
    OrganizationalUnitIdentifier: peer
