spring:
  datasource:
    url: jdbc:mysql://172.22.129.53:3306/bclux
    username: root
    password: 124816
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    date-format: yyyy.MM.dd HH:mm:ss
  jackson:
    property-naming-strategy: SNAKE_CASE
  thymeleaf:
    cache: false
fabric:
  config:
    cert: |
      -----BEGIN CERTIFICATE-----
      MIICCTCCAbCgAwIBAgIRANDvNYEFVaHGglJiYmg5WyowCgYIKoZIzj0EAwIwXTEL
      MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
      cmFuY2lzY28xDjAMBgNVBAoTBUJyYW5kMREwDwYDVQQDEwhjYS5CcmFuZDAeFw0y
      MDA1MjEwMDM5MDBaFw0zMDA1MTkwMDM5MDBaMGExCzAJBgNVBAYTAlVTMRMwEQYD
      VQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMQ8wDQYDVQQL
      EwZjbGllbnQxFDASBgNVBAMMC0FkbWluQEJyYW5kMFkwEwYHKoZIzj0CAQYIKoZI
      zj0DAQcDQgAECuWp+gthxVZcVFeLUxgTvTQ5imQoTLmEArx37OSIjxHiHlElVtPN
      pSb+CSGjb1SYzwvEdLQNgtxfA4HHS4q0NKNNMEswDgYDVR0PAQH/BAQDAgeAMAwG
      A1UdEwEB/wQCMAAwKwYDVR0jBCQwIoAga4EzMx9Ydro5dOzPmmdI+AdGREbFZahR
      fyHoqT/Mq+kwCgYIKoZIzj0EAwIDRwAwRAIgfclYZ0CXlATsLU+aDw7q3OEKg0WV
      LtZijIozkoc/A+oCIByN32U/uxmmPSBZmkOW2iWdtZodgNlnAoog30uOv1nA
      -----END CERTIFICATE-----
    key: MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgCKe/3syQuPkWJbB7KVzrGif/wUkFWLu7zzK4Ae2UAK+hRANCAAQK5an6C2HFVlxUV4tTGBO9NDmKZChMuYQCvHfs5IiPEeIeUSVW082lJv4JIaNvVJjPC8R0tA2C3F8DgcdLirQ0
    ipAddress: 172.22.129.53
#debug: true