NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.Retailer1-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.Retailer1-cert.pem
    OrganizationalUnitIdentifier: peer
